version: '3'

services:
  rust-cubicle:
    build: .
    image: marionebl/rust-exercism-cubicle
    ports:
      - '8443:8443'
    volumes:
      - ".:/home/rust/src/"
    environment:
      - CARGO_TARGET_DIR=/home/rust/target
    command: code-server --allow-http --no-auth
