version: 2
jobs:
  build:
    docker:
      - image: marionebl/move_rs_dev
    working_directory: /home/rust/src
    steps:
      - checkout:
          path: /home/rust/repo
      - run:
          name: Mount sources
          command: cp -r /home/rust/repo/exercises exercises 
      - run:
          name: Test hello world
          command: cargo test -p hello-world