version: 2
jobs:
  build:
    docker:
      - image: marionebl/move_rs_dev
    working_directory: /home/rust/repo
    steps:
      - checkout:
          path: /home/rust/repo
      - run:
          name: Test hello world
          command: cargo test -p hello-world